<?php

/** @var \Hyva\Theme\Model\ViewModelRegistry $viewModels */
/** @var \Nuvei\Checkout\ViewModel\HyvaCheckoutViewModel $viewModel */

// Hyva's way to get your ViewModel without XML
$viewModel      = $viewModels->require(\Nuvei\Checkout\ViewModel\HyvaCheckoutViewModel::class);
$configJson     = $viewModel->getJsonConfig();

?>

<div>
    <div id="nuvei_checkout" 
         x-ignore
         x-data 
         data-config='<?= $escaper->escapeHtmlAttr($configJson) ?>'>
        Loading...
    </div>
    
    <div class="nuvei-loading-mask" 
         data-role="loader" 
         style="display: none; z-index: 9999; bottom: 0; left: 0; margin: auto; position: fixed; right: 0; top: 0; background: rgba(255,255,255,0.5);">
        <div class="loader">
            <img alt="Loading..." src="#" style="bottom: 0; left: 0; margin: auto; position: fixed; right: 0; top: 0; z-index: 100; max-width: 100%; height: auto; border: 0;" />
        </div>
    </div>
    
<!--    <template x-if="errorMessage">
        <div class="message error" x-text="errorMessage"></div>
    </template>-->
</div>
